server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          predicates:
            - Path=/api/v1/products/**
          uri: lb://PRODUCT-SERVICE
          filters:
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location
